### ISSUE TITLE
async generator assertion error

### ISSUE THREAD

**Issue by pohmelie** [python-trio/pytest-trio#85]
I write project with couple io backends, one of them is trio. Async generator is very useful pattern for fixtures. And I like to use it in tests with asyncio. I was very happy to see trio pytest plugin, but unfortunately it fails. Maybe I missed something?

test_something.py:
``` python
from functools import partial

import trio
import pytest
import pytest_trio


HOST = "127.0.0.1"
MESSAGE = b"work!"


@pytest_trio.trio_fixture
async def endpoint_port(nursery):
    port = 11011

    async def handler(stream):
        async with stream:
            b = await stream.receive_some(8192)
            await stream.send_all(b)

    await nursery.start(partial(trio.serve_tcp, handler, port, host=HOST))
    yield port


@pytest.mark.trio
async def test_connection_direct_success(endpoint_port):
    s = await trio.open_tcp_stream(HOST, endpoint_port)
    await s.send_all(MESSAGE)
    m = await s.receive_some(8192)
    assert m == MESSAGE
```
Run:
``` bash
pytest test_something.py
```
Cutted response:
```
                except TrioInternalError:
                    raise
                except BaseException as exc:
                    raise TrioInternalError(
                        "internal error in trio - please file a bug!"
>                   ) from exc
E                   trio.TrioInternalError: internal error in trio - please file a bug!

../../../.pyenv/versions/3.6.7/lib/python3.6/site-packages/trio/_core/_run.py:1436: TrioInternalError
------------------------------------------------------------------------------------- Captured log setup -------------------------------------------------------------------------------------
15:51:15.627 asyncio              DEBUG    selector_events.py 65   Using selector: EpollSelector

----------- coverage: platform linux, python 3.6.7-final-0 -----------
...
================================================================================== 1 failed in 0.18 seconds ==================================================================================
Exception ignored in: <bound method Nursery.__del__ of <trio._core._run.Nursery object at 0x7f856a1cd7f0>>
Traceback (most recent call last):
  File "/home/poh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/trio/_core/_run.py", line 638, in __del__
AssertionError: 
```
```

**Comment by oremanj** [comment]
I don't get any errors running the code you pasted. Could you supply the entire traceback including chained exceptions, and the versions of trio and of pytest-trio that you're using?

**Comment by pohmelie** [comment]
```
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.7, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/poh/pro/py/siosocks, inifile: pytest.ini
plugins: cov-2.7.1, trio-0.5.2, asyncio-0.10.0, xdist-1.28.0, forked-1.0.2
collected 1 item                                                                                                                                                                             

tests/test_trio2.py F                                                                                                                                                                  [100%]Coverage.py warning: No data was collected. (no-data-collected)


========================================================================================== FAILURES ==========================================================================================
_______________________________________________________________________________ test_connection_direct_success _______________________________________________________________________________

async_fn = functools.partial(<function _trio_test_runner_factory.<locals>._bootstrap_fixtures_and_run_test at 0x7fe7905738c8>, endpoint_port=<pytest_trio.plugin.TrioFixture object at 0x7fe791745fd0>)
clock = SystemClock(offset=84650.44820495433), instruments = [], restrict_keyboard_interrupt_to_checkpoints = False, args = ()

    def run(
        async_fn,
        *args,
        clock=None,
        instruments=(),
        restrict_keyboard_interrupt_to_checkpoints=False
    ):
        """Run a trio-flavored async function, and return the result.
    
        Calling::
    
           run(async_fn, *args)
    
        is the equivalent of::
    
           await async_fn(*args)
    
        except that :func:`run` can (and must) be called from a synchronous
        context.
    
        This is trio's main entry point. Almost every other function in trio
        requires that you be inside a call to :func:`run`.
    
        Args:
          async_fn: An async function.
    
          args: Positional arguments to be passed to *async_fn*. If you need to
              pass keyword arguments, then use :func:`functools.partial`.
    
          clock: ``None`` to use the default system-specific monotonic clock;
              otherwise, an object implementing the :class:`trio.abc.Clock`
              interface, like (for example) a :class:`trio.testing.MockClock`
              instance.
    
          instruments (list of :class:`trio.abc.Instrument` objects): Any
              instrumentation you want to apply to this run. This can also be
              modified during the run; see :ref:`instrumentation`.
    
          restrict_keyboard_interrupt_to_checkpoints (bool): What happens if the
              user hits control-C while :func:`run` is running? If this argument
              is False (the default), then you get the standard Python behavior: a
              :exc:`KeyboardInterrupt` exception will immediately interrupt
              whatever task is running (or if no task is running, then trio will
              wake up a task to be interrupted). Alternatively, if you set this
              argument to True, then :exc:`KeyboardInterrupt` delivery will be
              delayed: it will be *only* be raised at :ref:`checkpoints
              <checkpoints>`, like a :exc:`Cancelled` exception.
    
              The default behavior is nice because it means that even if you
              accidentally write an infinite loop that never executes any
              checkpoints, then you can still break out of it using control-C.
              The alternative behavior is nice if you're paranoid about a
              :exc:`KeyboardInterrupt` at just the wrong place leaving your
              program in an inconsistent state, because it means that you only
              have to worry about :exc:`KeyboardInterrupt` at the exact same
              places where you already have to worry about :exc:`Cancelled`.
    
              This setting has no effect if your program has registered a custom
              SIGINT handler, or if :func:`run` is called from anywhere but the
              main thread (this is a Python limitation), or if you use
              :func:`open_signal_receiver` to catch SIGINT.
    
        Returns:
          Whatever ``async_fn`` returns.
    
        Raises:
          TrioInternalError: if an unexpected error is encountered inside trio's
              internal machinery. This is a bug and you should `let us know
              <https://github.com/python-trio/trio/issues>`__.
    
          Anything else: if ``async_fn`` raises an exception, then :func:`run`
              propagates it.
    
        """
    
        __tracebackhide__ = True
    
        # Do error-checking up front, before we enter the TrioInternalError
        # try/catch
        #
        # It wouldn't be *hard* to support nested calls to run(), but I can't
        # think of a single good reason for it, so let's be conservative for
        # now:
        if hasattr(GLOBAL_RUN_CONTEXT, "runner"):
            raise RuntimeError("Attempted to call run() from inside a run()")
    
        if clock is None:
            clock = SystemClock()
        instruments = list(instruments)
        io_manager = TheIOManager()
        system_context = copy_context()
        system_context.run(current_async_library_cvar.set, "trio")
        runner = Runner(
            clock=clock,
            instruments=instruments,
            io_manager=io_manager,
            system_context=system_context,
        )
        GLOBAL_RUN_CONTEXT.runner = runner
        locals()[LOCALS_KEY_KI_PROTECTION_ENABLED] = True
    
        # KI handling goes outside the core try/except/finally to avoid a window
        # where KeyboardInterrupt would be allowed and converted into an
        # TrioInternalError:
        try:
            with ki_manager(
                runner.deliver_ki, restrict_keyboard_interrupt_to_checkpoints
            ):
                try:
                    with closing(runner):
                        # The main reason this is split off into its own function
                        # is just to get rid of this extra indentation.
>                       run_impl(runner, async_fn, args)

../../../.pyenv/versions/3.6.7/lib/python3.6/site-packages/trio/_core/_run.py:1430: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

runner = Runner(clock=SystemClock(offset=84650.44820495433), instruments=[], io_manager=EpollIOManager(_epoll=<select.epoll obj...d.RLock object owner=0 count=0 at 0x7fe79056d510>), trio_token=None, ki_pending=False, waiting_for_idle=SortedDict({}))
async_fn = functools.partial(<function _trio_test_runner_factory.<locals>._bootstrap_fixtures_and_run_test at 0x7fe7905738c8>, endpoint_port=<pytest_trio.plugin.TrioFixture object at 0x7fe791745fd0>)
args = ()

    def run_impl(runner, async_fn, args):
        __tracebackhide__ = True
    
        if runner.instruments:
            runner.instrument("before_run")
        runner.clock.start_clock()
        runner.init_task = runner.spawn_impl(
            runner.init,
            (async_fn, args),
            None,
            "<init>",
            system_task=True,
        )
    
        # You know how people talk about "event loops"? This 'while' loop right
        # here is our event loop:
        while runner.tasks:
            if runner.runq:
                timeout = 0
            elif runner.deadlines:
                deadline, _ = runner.deadlines.keys()[0]
                timeout = runner.clock.deadline_to_sleep_time(deadline)
            else:
                timeout = _MAX_TIMEOUT
            timeout = min(max(0, timeout), _MAX_TIMEOUT)
    
            idle_primed = False
            if runner.waiting_for_idle:
                cushion, tiebreaker, _ = runner.waiting_for_idle.keys()[0]
                if cushion < timeout:
                    timeout = cushion
                    idle_primed = True
    
            if runner.instruments:
                runner.instrument("before_io_wait", timeout)
    
            runner.io_manager.handle_io(timeout)
    
            if runner.instruments:
                runner.instrument("after_io_wait", timeout)
    
            # Process cancellations due to deadline expiry
            now = runner.clock.current_time()
            while runner.deadlines:
                (deadline, _), cancel_scope = runner.deadlines.peekitem(0)
                if deadline <= now:
                    # This removes the given scope from runner.deadlines:
                    cancel_scope.cancel()
                    idle_primed = False
                else:
                    break
    
            if not runner.runq and idle_primed:
                while runner.waiting_for_idle:
                    key, task = runner.waiting_for_idle.peekitem(0)
                    if key[:2] == (cushion, tiebreaker):
                        del runner.waiting_for_idle[key]
                        runner.reschedule(task)
                    else:
                        break
    
            # Process all runnable tasks, but only the ones that are already
            # runnable now. Anything that becomes runnable during this cycle needs
            # to wait until the next pass. This avoids various starvation issues
            # by ensuring that there's never an unbounded delay between successive
            # checks for I/O.
            #
            # Also, we randomize the order of each batch to avoid assumptions
            # about scheduling order sneaking in. In the long run, I suspect we'll
            # either (a) use strict FIFO ordering and document that for
            # predictability/determinism, or (b) implement a more sophisticated
            # scheduler (e.g. some variant of fair queueing), for better behavior
            # under load. For now, this is the worst of both worlds - but it keeps
            # our options open. (If we do decide to go all in on deterministic
            # scheduling, then there are other things that will probably need to
            # change too, like the deadlines tie-breaker and the non-deterministic
            # ordering of task._notify_queues.)
            batch = list(runner.runq)
            if _ALLOW_DETERMINISTIC_SCHEDULING:
                # We're running under Hypothesis, and pytest-trio has patched this
                # in to make the scheduler deterministic and avoid flaky tests.
                # It's not worth the (small) performance cost in normal operation,
                # since we'll shuffle the list and _r is only seeded for tests.
                batch.sort(key=lambda t: t._counter)
            runner.runq.clear()
            _r.shuffle(batch)
            while batch:
                task = batch.pop()
                GLOBAL_RUN_CONTEXT.task = task
    
                if runner.instruments:
                    runner.instrument("before_task_step", task)
    
                next_send = task._next_send
                task._next_send = None
                final_outcome = None
                try:
                    # We used to unwrap the Outcome object here and send/throw its
                    # contents in directly, but it turns out that .throw() is
                    # buggy, at least on CPython 3.6 and earlier:
                    #   https://bugs.python.org/issue29587
                    #   https://bugs.python.org/issue29590
                    # So now we send in the Outcome object and unwrap it on the
                    # other side.
                    msg = task.context.run(task.coro.send, next_send)
                except StopIteration as stop_iteration:
                    final_outcome = Value(stop_iteration.value)
                except BaseException as task_exc:
                    # Store for later, removing uninteresting top frames: 1 frame
                    # we always remove, because it's this function catching it,
                    # and then in addition we remove however many more Context.run
                    # adds.
                    tb = task_exc.__traceback__.tb_next
                    for _ in range(CONTEXT_RUN_TB_FRAMES):
                        tb = tb.tb_next
                    final_outcome = Error(task_exc.with_traceback(tb))
    
                if final_outcome is not None:
                    # We can't call this directly inside the except: blocks above,
                    # because then the exceptions end up attaching themselves to
                    # other exceptions as __context__ in unwanted ways.
>                   runner.task_exited(task, final_outcome)

../../../.pyenv/versions/3.6.7/lib/python3.6/site-packages/trio/_core/_run.py:1579: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Runner(clock=SystemClock(offset=84650.44820495433), instruments=[], io_manager=EpollIOManager(_epoll=<select.epoll obj...d.RLock object owner=0 count=0 at 0x7fe79056d510>), trio_token=None, ki_pending=False, waiting_for_idle=SortedDict({}))
task = <Task "<fixture 'endpoint_port'>" at 0x7fe7905d6c50>, outcome = Error(RuntimeError('cannot reuse already awaited coroutine',))

    def task_exited(self, task, outcome):
        while task._cancel_stack:
            task._cancel_stack[-1]._remove_task(task)
>       self.tasks.remove(task)
E       KeyError: <Task "<fixture 'endpoint_port'>" at 0x7fe7905d6c50>

../../../.pyenv/versions/3.6.7/lib/python3.6/site-packages/trio/_core/_run.py:1051: KeyError

The above exception was the direct cause of the following exception:

async_fn = functools.partial(<function _trio_test_runner_factory.<locals>._bootstrap_fixtures_and_run_test at 0x7fe7905738c8>, endpoint_port=<pytest_trio.plugin.TrioFixture object at 0x7fe791745fd0>)
clock = SystemClock(offset=84650.44820495433), instruments = [], restrict_keyboard_interrupt_to_checkpoints = False, args = ()

    def run(
        async_fn,
        *args,
        clock=None,
        instruments=(),
        restrict_keyboard_interrupt_to_checkpoints=False
    ):
        """Run a trio-flavored async function, and return the result.
    
        Calling::
    
           run(async_fn, *args)
    
        is the equivalent of::
    
           await async_fn(*args)
    
        except that :func:`run` can (and must) be called from a synchronous
        context.
    
        This is trio's main entry point. Almost every other function in trio
        requires that you be inside a call to :func:`run`.
    
        Args:
          async_fn: An async function.
    
          args: Positional arguments to be passed to *async_fn*. If you need to
              pass keyword arguments, then use :func:`functools.partial`.
    
          clock: ``None`` to use the default system-specific monotonic clock;
              otherwise, an object implementing the :class:`trio.abc.Clock`
              interface, like (for example) a :class:`trio.testing.MockClock`
              instance.
    
          instruments (list of :class:`trio.abc.Instrument` objects): Any
              instrumentation you want to apply to this run. This can also be
              modified during the run; see :ref:`instrumentation`.
    
          restrict_keyboard_interrupt_to_checkpoints (bool): What happens if the
              user hits control-C while :func:`run` is running? If this argument
              is False (the default), then you get the standard Python behavior: a
              :exc:`KeyboardInterrupt` exception will immediately interrupt
              whatever task is running (or if no task is running, then trio will
              wake up a task to be interrupted). Alternatively, if you set this
              argument to True, then :exc:`KeyboardInterrupt` delivery will be
              delayed: it will be *only* be raised at :ref:`checkpoints
              <checkpoints>`, like a :exc:`Cancelled` exception.
    
              The default behavior is nice because it means that even if you
              accidentally write an infinite loop that never executes any
              checkpoints, then you can still break out of it using control-C.
              The alternative behavior is nice if you're paranoid about a
              :exc:`KeyboardInterrupt` at just the wrong place leaving your
              program in an inconsistent state, because it means that you only
              have to worry about :exc:`KeyboardInterrupt` at the exact same
              places where you already have to worry about :exc:`Cancelled`.
    
              This setting has no effect if your program has registered a custom
              SIGINT handler, or if :func:`run` is called from anywhere but the
              main thread (this is a Python limitation), or if you use
              :func:`open_signal_receiver` to catch SIGINT.
    
        Returns:
          Whatever ``async_fn`` returns.
    
        Raises:
          TrioInternalError: if an unexpected error is encountered inside trio's
              internal machinery. This is a bug and you should `let us know
              <https://github.com/python-trio/trio/issues>`__.
    
          Anything else: if ``async_fn`` raises an exception, then :func:`run`
              propagates it.
    
        """
    
        __tracebackhide__ = True
    
        # Do error-checking up front, before we enter the TrioInternalError
        # try/catch
        #
        # It wouldn't be *hard* to support nested calls to run(), but I can't
        # think of a single good reason for it, so let's be conservative for
        # now:
        if hasattr(GLOBAL_RUN_CONTEXT, "runner"):
            raise RuntimeError("Attempted to call run() from inside a run()")
    
        if clock is None:
            clock = SystemClock()
        instruments = list(instruments)
        io_manager = TheIOManager()
        system_context = copy_context()
        system_context.run(current_async_library_cvar.set, "trio")
        runner = Runner(
            clock=clock,
            instruments=instruments,
            io_manager=io_manager,
            system_context=system_context,
        )
        GLOBAL_RUN_CONTEXT.runner = runner
        locals()[LOCALS_KEY_KI_PROTECTION_ENABLED] = True
    
        # KI handling goes outside the core try/except/finally to avoid a window
        # where KeyboardInterrupt would be allowed and converted into an
        # TrioInternalError:
        try:
            with ki_manager(
                runner.deliver_ki, restrict_keyboard_interrupt_to_checkpoints
            ):
                try:
                    with closing(runner):
                        # The main reason this is split off into its own function
                        # is just to get rid of this extra indentation.
                        run_impl(runner, async_fn, args)
                except TrioInternalError:
                    raise
                except BaseException as exc:
                    raise TrioInternalError(
                        "internal error in trio - please file a bug!"
>                   ) from exc
E                   trio.TrioInternalError: internal error in trio - please file a bug!

../../../.pyenv/versions/3.6.7/lib/python3.6/site-packages/trio/_core/_run.py:1436: TrioInternalError
------------------------------------------------------------------------------------- Captured log setup -------------------------------------------------------------------------------------
16:25:52.770 asyncio              DEBUG    selector_events.py 65   Using selector: EpollSelector

----------- coverage: platform linux, python 3.6.7-final-0 -----------
Name                      Stmts   Miss  Cover   Missing
-------------------------------------------------------
siosocks/__init__.py          2      2     0%   1-2
siosocks/interface.py        32     32     0%   1-60
siosocks/io/__init__.py       0      0   100%
siosocks/io/asyncio.py       72     72     0%   1-107
siosocks/io/const.py          1      1     0%   1
siosocks/io/socket.py        49     49     0%   1-69
siosocks/io/trio.py          64     64     0%   1-95
siosocks/protocol.py        208    208     0%   1-278
siosocks/sansio.py           68     68     0%   1-86
-------------------------------------------------------
TOTAL                       496    496     0%
Coverage XML written to file coverage.xml

================================================================================= slowest 10 test durations ==================================================================================

(0.00 durations hidden.  Use -vv to show these durations.)
================================================================================== 1 failed in 0.18 seconds ==================================================================================
Exception ignored in: <bound method Nursery.__del__ of <trio._core._run.Nursery object at 0x7fe7905d6b70>>
Traceback (most recent call last):
  File "/home/poh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/trio/_core/_run.py", line 638, in __del__
AssertionError: 
Exception ignored in: <bound method Nursery.__del__ of <trio._core._run.Nursery object at 0x7fe7905c5d68>>
Traceback (most recent call last):
  File "/home/poh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/trio/_core/_run.py", line 638, in __del__
AssertionError: 
```

**Comment by pohmelie** [comment]
Ok, I found the problem. If I remove `pytest-asyncio`, then tests are ok. But I don't understand why `pytest-asyncio` affects.

**Comment by pohmelie** [comment]
Oh, looks like this is raised already https://github.com/pytest-dev/pytest-asyncio/issues/124

**Comment by oremanj** [comment]
Sure enough, with pytest-asyncio installed I'm able to reproduce this. If I dig into the traceback a bit I find
```
(Pdb) p sys.last_value
TrioInternalError('internal error in trio - please file a bug!',)
(Pdb) exc = sys.last_value
(Pdb) p exc.__cause__.__traceback__.tb_next.tb_next.tb_frame.f_code
<code object task_exited at 0x7f2a3fd908a0, file "/usr/scratch/trio/trio/_core/_run.py", line 1050>
(Pdb) p exc.__cause__.__traceback__.tb_next.tb_next.tb_frame.f_locals['outcome']
Error(RuntimeError('cannot reuse already awaited coroutine',))
(Pdb) p exc.__cause__.__traceback__.tb_next.tb_next.tb_frame.f_locals['outcome'].error.__traceback__
None
```
The `outcome` passed to `task_exited` contains the thing raised when we tried to run the task. Since there's no traceback frames attached, it must have been raised directly when we called `send()` on the coroutine. Which is:
```
(Pdb) p exc.__cause__.__traceback__.tb_next.tb_frame.f_locals['task']
<Task "<fixture 'endpoint_port'>" at 0x7f2a3f0d5be0>
(Pdb) p exc.__cause__.__traceback__.tb_next.tb_frame.f_locals['task'].coro
<coroutine object TrioFixture.run at 0x7f2a3f0d6780>
```
So yeah, this looks like pytest-asyncio treating your Trio fixture as an asyncio fixture too, meaning we try to run it twice and havoc results. This one's on pytest-asyncio to fix, I'm afraid; there's not much that pytest-trio can do about it.

**Comment by pohmelie** [comment]
Ok, thank you!
